// Code generated by go-swagger; DO NOT EDIT.

package image

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	timeext "time"
)

// SignatureTimestamp SignatureTimestamp contains information about a verified signed timestamp for an image signature.
//
// swagger:model SignatureTimestamp
type SignatureTimestamp struct {

	// timestamp
	// Example: 2016-10-19T04:33:30.360899459Z
	// Format: date-time
	Timestamp timeext.Time `json:"Timestamp,omitempty"`

	// type
	Type SignatureTimestampType `json:"Type,omitempty"`

	// URI
	URI string `json:"URI,omitempty"`
}
